import "@/styles/index.css" //global styles
import Header from "@/components/Header"

export const metadata = {
  title: "Next app template",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body suppressHydrationWarning={true}>
        <div className="app-container">
          <Header />
          <div className="page-container">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
