import "@/styles/index.css" //global styles
import Header from "@/components/Header"



interface Metadata {
  title: string,
  description: string
}
export const metadata: Metadata = {
  title: "Next app template",
  description: "Generated by create next app",
}


interface Props {
  children: React.ReactNode
}
const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang="en" >
      <body suppressHydrationWarning={true}>
        <div className="app-container">
          <Header />
          <div className="page-container">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}

export default RootLayout
